name = "FFTV"
author = "packwiz init"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f9c55b106396d75bf5aba0a1640a8a9997ef88c0f41327cfbf2376cac774ed85"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"
