name = "FFTV"
author = "packwiz init"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c22eef0c3262275bcda9b495cce28dadec6f984e826120df942fcaa9c35f34fe"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"
